// Generated by CoffeeScript 1.9.2
(function() {
  var Base64;

  Base64 = function() {
    this.e = function(a) {
      return window.btoa(unescape(encodeURIComponent(a)));
    };
    this.d = function(a) {
      return decodeURIComponent(escape(window.atob(a)));
    };
    this["eval"] = function(a) {
      return eval(decodeURIComponent(escape(window.atob(a))));
    };
  };

  window.Base64 = new Base64;

}).call(this);
